name: Run Python Script on Schedule

on:
  # This cron syntax schedules the job. This example runs it every day at midnight UTC.
  schedule:
    - cron: '*/5 * * * *'  # Runs every day at midnight (UTC)
  workflow_dispatch:  # This allows you to trigger the workflow manually if needed

jobs:
  run:
    runs-on: ubuntu-latest  # The environment the job runs in (Ubuntu server)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Check out the repository so we can run the script

      - name: Set up Python
        uses: actions/setup-python@v2  # Set up Python environment
        with:
          python-version: '3.x'  # Specify Python version you need (e.g., '3.x' for latest Python 3)

      - name: Run the Python script
        run: |
          python Smartsheets_Event_Trigger.py  # Run your script (replace with your actual script name)
