name: Run Python Script via Power Automate

on:
  workflow_dispatch:  # Allows manual triggering from GitHub Actions UI
  repository_dispatch:  # Enables triggering via API (used by Power Automate)
    types:
      - trigger-python-script  # Custom event type for triggering

jobs:
  run:
    runs-on: ubuntu-latest  # The environment the job runs in (Ubuntu server)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Check out the repository to access code

      - name: Set up Python
        uses: actions/setup-python@v2  # Set up Python environment
        with:
          python-version: '3.x'  # Specify Python version (e.g., '3.x' for latest Python 3)

      - name: Install Dependencies
        run: |
          pip install smartsheet-python-sdk  # Install required dependencies

      - name: Run the Python script
        run: |
          python Smartsheets_Event_Trigger.py  # Run the specified Python script
